# Generated by Django 6.0.2 on 2026-03-17 01:08

import datetime
import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.validador_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de Nascimento', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Insira um CPF válido', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validador_cpf.validacao_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Disciplina', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(help_text='Sigla da Disciplina', max_length=5, validators=[django.core.validators.MinLengthValidator(3)])),
                ('semestre', models.IntegerField(help_text='Semestre da Disciplina', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ementa', models.TextField(help_text='Ementa da Disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='E-mail institucional do aluno', max_length=255, verbose_name='E-mail')),
                ('cod', models.CharField(help_text='Digite a matrícula do aluno', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Matrícula')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='Insira o e-mail institucional', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Digite o número do passaporte', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Número do passaporte')),
                ('emissao', models.DateField(help_text='Selecione a data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de emissão')),
                ('vencimento', models.DateField(help_text='Selecione a data de vencimento do passaporte', verbose_name='Vencimento do passaporte')),
                ('pessoa', models.OneToOneField(help_text='Selecione o titular do passaporte', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da revista', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('edicao', models.IntegerField(help_text='Edição da revista', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição')),
            ],
            options={
                'unique_together': {('nome', 'edicao')},
            },
        ),
        migrations.CreateModel(
            name='Reportagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título da reportagem', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título')),
                ('publicacao', models.DateField(help_text='Insira a data da publicação', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Publicação')),
                ('revistas', models.ManyToManyField(help_text='Selecione as revistas nas quais a reportagem foi publicada', to='relacionamentos.revista')),
            ],
            options={
                'verbose_name_plural': 'Reportagens',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Insira a data da matrícula')),
                ('nota', models.FloatField(help_text='Nota final do aluno', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('frequencia', models.FloatField(help_text='Informe a frequência final do aluno', verbose_name='Frequência')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Aprovado em exame', 'Aprovado em exame'), ('Em Exame', 'Em Exame'), ('Matriculado', 'Matriculado'), ('Reprovado', 'Reprovado'), ('Trancado', 'Trancado')], default='Matriculado', help_text='Status do aluno para a matrícula', max_length=20)),
                ('disciplina', models.ForeignKey(help_text='Selecione a disciplina para o aluno', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.disciplina')),
                ('aluno', models.ForeignKey(help_text='Selecione o aluno para a matrícula', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(help_text='Selecione as disciplinas do aluno', through='relacionamentos.Matricula', through_fields=('aluno', 'disciplina'), to='relacionamentos.disciplina'),
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do artigo', max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('publicacao', models.DateField(help_text='Selecione a data da publicação', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Publicação')),
                ('reporter', models.ForeignKey(help_text='Selecione o autor do artigo', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Reporter Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
