# Generated by Django 6.0.2 on 2026-03-12 23:08

import django.core.validators
import relacionamentos.validators.validador_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=100, validators=[django.core.validators.MinValueValidator(5)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de Nascimento', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Insira um CPF válido', max_length=11, unique=True, validators=[django.core.validators.MinValueValidator(11), relacionamentos.validators.validador_cpf.validacao_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
