# Generated by Django 6.0.2 on 2026-03-12 23:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0002_alter_pessoa_cpf_alter_pessoa_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Digite o número do passaporte', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Número do passaporte')),
                ('emissao', models.DateField(help_text='Selecione a data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 3, 12))], verbose_name='Data de emissão')),
                ('vencimento', models.DateField(help_text='Selecione a data de vencimento do passaporte', verbose_name='Vencimento do passaporte')),
                ('pessoa', models.OneToOneField(help_text='Selecione o titular do passaporte', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
