# Generated by Django 6.0.2 on 2026-03-12 23:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0003_passaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passaporte',
            name='emissao',
            field=models.DateField(help_text='Selecione a data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de emissão'),
        ),
    ]
