# Generated by Django 6.0.2 on 2026-03-13 00:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0004_alter_passaporte_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='Insira o e-mail institucional', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.AlterField(
            model_name='passaporte',
            name='emissao',
            field=models.DateField(help_text='Selecione a data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(help_text='Selecione a data de Nascimento', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
    ]
