# Generated by Django 6.0.2 on 2026-03-13 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0006_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da revista', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('edicao', models.IntegerField(help_text='Edição da revista', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição')),
            ],
            options={
                'unique_together': {('nome', 'edicao')},
            },
        ),
    ]
