# Generated by Django 6.0.2 on 2026-03-03 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_categoria_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade_de_itens', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='area',
            field=models.CharField(blank=True, help_text='Informe a area de conhecimento', max_length=20, null=True, verbose_name='Area do conhecimento'),
        ),
    ]
