# Generated by Django 6.0.2 on 2026-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_compras_alter_categoria_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade_de_itens', models.IntegerField()),
                ('peso', models.FloatField()),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
