# Generated by Django 6.0.2 on 2026-03-05 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0005_compra_delete_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(help_text='Código do problema', unique=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('titulo', models.CharField(help_text='Título do probema', max_length=100, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Título')),
                ('nivel', models.IntegerField(choices=[(1, 'Um'), (2, 'Dois'), (3, 'Tres'), (4, 'Quatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Sete'), (8, 'Oito'), (9, 'Nove'), (10, 'Dez')], default=1, help_text='Escolha o nível do problema', verbose_name='Nível')),
                ('descricao', models.TextField(help_text='Insira a descrição do problema para o usuário', max_length=2000, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Descrição')),
                ('exemplo_entrada', models.TextField(help_text='Entrada para a solução do problema', max_length=2000, verbose_name='Exemplo de entrada')),
                ('exemplo_saida', models.TextField(help_text='Saída esperada para a solução do problema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Saída esperada')),
                ('pontuacao', models.FloatField(help_text='Insira a pontuação a ser creditada para o usuário', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Pontuação')),
                ('tempo_execucao', models.IntegerField(help_text='Insira ao tempo máximo de exxecução', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Tempo de execução do programa')),
                ('memoria_maxima', models.IntegerField(help_text='Informe a quantidade em MB de memória a ser utilizada', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(256)], verbose_name='Memória Máxima')),
                ('resolvidos', models.IntegerField(help_text='Quantidade de usuários que resolveram o problema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resolvido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
