# Generated by Django 6.0.2 on 2026-03-06 00:34

import django.core.validators
import exemplo.validators.validador_memoria
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0006_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='cod',
            field=models.IntegerField(help_text='Código do problema', unique=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='descricao',
            field=models.TextField(help_text='Insira a descrição do problema para o usuário', max_length=2000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='memoria_maxima',
            field=models.IntegerField(help_text='Informe a quantidade em MB de memória a ser utilizada', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(256), exemplo.validators.validador_memoria.ValidarTamanhhoMemoria], verbose_name='Memória Máxima'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='nivel',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Escolha o nível do problema', verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='resolvidos',
            field=models.IntegerField(default=0, help_text='Quantidade de usuários que resolveram o problema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resolvido'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='tempo_execucao',
            field=models.IntegerField(help_text='Insira o tempo máximo de execução', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Tempo de execução do programa'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(help_text='Título do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título'),
        ),
    ]
