# Generated by Django 6.0.2 on 2026-03-06 01:11

import django.core.validators
import exemplo.validators.palavras_proibidas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0007_alter_problema_cod_alter_problema_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='descricao',
            field=models.TextField(help_text='Insira a descrição do problema para o usuário', max_length=2000, validators=[django.core.validators.MinLengthValidator(20), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['irã', 'trump', 'eua'], mensagem='Você utilizou palavras proibidas. Revise as diretrizes das questões.')], verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(help_text='Título do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='O campo palavras que foram proibidas foram detectados')], verbose_name='Título'),
        ),
    ]
