# Generated by Django 6.0.2 on 2026-03-12 22:30

import django.core.validators
import exemplo.validators.palavras_proibidas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0008_alter_problema_descricao_alter_problema_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(help_text='Título do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='O campo contém palavras que foram proibidas. Ex: teste, admin')], verbose_name='Título'),
        ),
    ]
