# Generated by Django 6.0.2 on 2026-03-27 01:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0009_alter_problema_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Cidade', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(help_text='Insira a sigla do estado', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para do esporte', max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para o time', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Pessoa', max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], help_text='Selecione o Sexo', max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('idade', models.IntegerField(help_text='Insira a Idade', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(200)])),
                ('renda', models.DecimalField(decimal_places=2, help_text='Adicione a Renda', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo.cidade')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo.esporte')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo.time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
